/**
 * Generates supabase/functions/_shared/blog-index-generated.ts from
 * src/data/blogArticles.ts. This compact index gives the AI chat and
 * voice agents a reference to every published blog post (slug, title,
 * description, category, keywords, FAQs) without bloating prompts.
 *
 * Run: npm run generate:blog-index
 */
import { blogArticles } from "../src/data/blogArticles";
import { createHash } from "node:crypto";
import { writeFileSync } from "node:fs";
import { resolve } from "node:path";

type SlimFaq = { q: string; a: string };
type SlimArticle = {
  slug: string;
  title: string;
  description: string;
  category: string;
  publishDate: string;
  keywords: string[];
  faqs: SlimFaq[];
};

const TRUNC = (s: string, n: number) =>
  s && s.length > n ? s.slice(0, n - 1).trimEnd() + "…" : s || "";

const slim: SlimArticle[] = blogArticles.map((a) => ({
  slug: a.slug,
  title: a.title,
  description: TRUNC(a.description || "", 240),
  category: a.category || "",
  publishDate: a.publishDate || a.datePublished || "",
  keywords: (a.keywords || []).slice(0, 8),
  faqs: (a.faqs || []).slice(0, 4).map((f) => ({
    q: TRUNC(f.question, 160),
    a: TRUNC(f.answer, 320),
  })),
}));

const header = `// AUTO-GENERATED by scripts/generate-blog-index.ts — do not edit by hand.
// Regenerate with: npm run generate:blog-index
// Source: src/data/blogArticles.ts (${slim.length} articles)

export interface BlogIndexFaq { q: string; a: string }
export interface BlogIndexEntry {
  slug: string;
  title: string;
  description: string;
  category: string;
  publishDate: string;
  keywords: string[];
  faqs: BlogIndexFaq[];
}

export const BLOG_INDEX: BlogIndexEntry[] = `;

const out = header + JSON.stringify(slim, null, 2) + ";\n";
const dest = resolve("supabase/functions/_shared/blog-index-generated.ts");
writeFileSync(dest, out, "utf8");

const publicDest = resolve("public/blog-index.json");
// The public index is also the live retrieval catalogue for chat and voice.
// Keep the payload bounded, but retain summaries, keywords and structured FAQs
// so a normal site deploy refreshes article knowledge without an Edge redeploy.
const publicArticles = slim;
const sourceVersion = createHash("sha256")
  .update(JSON.stringify(publicArticles))
  .digest("hex")
  .slice(0, 20);
writeFileSync(publicDest, JSON.stringify({
  version: 1,
  sourceVersion,
  count: publicArticles.length,
  articles: publicArticles,
}, null, 2) + "\n", "utf8");

console.log(`Wrote ${slim.length} articles → ${dest}`);
console.log(`Wrote ${slim.length} articles → ${publicDest} (${sourceVersion})`);
