/**
 * Generates supabase/functions/_shared/blog-index-generated.ts from
 * src/data/blogArticles.ts. This compact index gives the AI chat and
 * voice agents a reference to every published blog post (slug, title,
 * description, category, keywords, FAQs) without bloating prompts.
 *
 * Run:  bun run scripts/generate-blog-index.ts
 */
import { blogArticles } from "../src/data/blogArticles";
import { writeFileSync } from "node:fs";
import { resolve } from "node:path";

type SlimFaq = { q: string; a: string };
type SlimArticle = {
  slug: string;
  title: string;
  description: string;
  category: string;
  publishDate: string;
  keywords: string[];
  faqs: SlimFaq[];
};

const TRUNC = (s: string, n: number) =>
  s && s.length > n ? s.slice(0, n - 1).trimEnd() + "…" : s || "";

const slim: SlimArticle[] = blogArticles.map((a) => ({
  slug: a.slug,
  title: a.title,
  description: TRUNC(a.description || "", 240),
  category: a.category || "",
  publishDate: a.publishDate || a.datePublished || "",
  keywords: (a.keywords || []).slice(0, 8),
  faqs: (a.faqs || []).slice(0, 4).map((f) => ({
    q: TRUNC(f.question, 160),
    a: TRUNC(f.answer, 320),
  })),
}));

const header = `// AUTO-GENERATED by scripts/generate-blog-index.ts — do not edit by hand.
// Regenerate with: bun run scripts/generate-blog-index.ts
// Source: src/data/blogArticles.ts (${slim.length} articles)

export interface BlogIndexFaq { q: string; a: string }
export interface BlogIndexEntry {
  slug: string;
  title: string;
  description: string;
  category: string;
  publishDate: string;
  keywords: string[];
  faqs: BlogIndexFaq[];
}

export const BLOG_INDEX: BlogIndexEntry[] = `;

const out = header + JSON.stringify(slim, null, 2) + ";\n";
const dest = resolve("supabase/functions/_shared/blog-index-generated.ts");
writeFileSync(dest, out, "utf8");
console.log(`Wrote ${slim.length} articles → ${dest}`);
