-- Create public storage bucket for quotes PDFs if it doesn't exist
insert into storage.buckets (id, name, public)
values ('quotes', 'quotes', true)
on conflict (id) do nothing;

-- Storage policies for the quotes bucket
-- Public can read files in quotes bucket
create policy if not exists "Public can read quotes PDFs"
  on storage.objects
  for select
  using (bucket_id = 'quotes');

-- Allow anonymous uploads to quotes bucket (PDFs generated by the app)
create policy if not exists "Anon can upload quotes PDFs"
  on storage.objects
  for insert
  with check (bucket_id = 'quotes');

-- Create quotes table to store quote records
create table if not exists public.quotes (
  id uuid primary key default gen_random_uuid(),
  customer_name text,
  customer_phone text,
  motor_model text,
  motor_price numeric,
  total_price numeric,
  pdf_url text,
  quote_data jsonb,
  created_at timestamptz not null default now()
);

-- Enable RLS
alter table public.quotes enable row level security;

-- Policies: allow anyone to insert a quote (no auth in iframe context)
create policy if not exists "Anyone can insert quotes"
  on public.quotes
  for insert
  to anon
  with check (true);

-- Allow anyone to read quotes (e.g., for sharing)
create policy if not exists "Quotes are viewable by everyone"
  on public.quotes
  for select
  using (true);

-- Optional index for created_at
create index if not exists quotes_created_at_idx on public.quotes (created_at desc);