-- Private HBW RPCs are served through the signed service-role gateway.
-- Keep public quote/auth helpers and secret-gated worker writes unchanged.
REVOKE EXECUTE ON FUNCTION public.call_transcription_context(text,text,text,integer) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.call_transcription_context(text,text,text,integer) TO service_role;
REVOKE EXECUTE ON FUNCTION public.customer_brief(text,integer) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.customer_brief(text,integer) TO service_role;
REVOKE EXECUTE ON FUNCTION public.customer_issue_history(text,text,integer) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.customer_issue_history(text,text,integer) TO service_role;
REVOKE EXECUTE ON FUNCTION public.customer_lookup(text,integer) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.customer_lookup(text,integer) TO service_role;
REVOKE EXECUTE ON FUNCTION public.customer_match_candidates(text,integer) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.customer_match_candidates(text,integer) TO service_role;
REVOKE EXECUTE ON FUNCTION public.customer_product_history(text,text,date,date,integer) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.customer_product_history(text,text,date,date,integer) TO service_role;
REVOKE EXECUTE ON FUNCTION public.customer_service_parts_used(text,text,date,date,integer) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.customer_service_parts_used(text,text,date,date,integer) TO service_role;
REVOKE EXECUTE ON FUNCTION public.customer_service_red_flags(text,text,date,date,integer) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.customer_service_red_flags(text,text,date,date,integer) TO service_role;
REVOKE EXECUTE ON FUNCTION public.customer_service_work_summary(text,text,date,date,integer) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.customer_service_work_summary(text,text,date,date,integer) TO service_role;
REVOKE EXECUTE ON FUNCTION public.customer_units_summary(text,integer) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.customer_units_summary(text,integer) TO service_role;
REVOKE EXECUTE ON FUNCTION public.hbw_bot_admin_status() FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.hbw_bot_admin_status() TO service_role;
REVOKE EXECUTE ON FUNCTION public.hbw_bot_feedback_summary(integer) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.hbw_bot_feedback_summary(integer) TO service_role;
REVOKE EXECUTE ON FUNCTION public.hbw_bot_thread_context(text,text) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.hbw_bot_thread_context(text,text) TO service_role;
REVOKE EXECUTE ON FUNCTION public.hbw_call_transcription_phone_candidates(text[]) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.hbw_call_transcription_phone_candidates(text[]) TO service_role;
REVOKE EXECUTE ON FUNCTION public.hbw_twilio_customer_candidates(text) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.hbw_twilio_customer_candidates(text) TO service_role;
REVOKE EXECUTE ON FUNCTION public.hbw_twilio_pick_open_ro(bigint,text,timestamp with time zone) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.hbw_twilio_pick_open_ro(bigint,text,timestamp with time zone) TO service_role;
REVOKE EXECUTE ON FUNCTION public.last_service_summary(text,integer) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.last_service_summary(text,integer) TO service_role;
REVOKE EXECUTE ON FUNCTION public.open_ro_brief(text,integer) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.open_ro_brief(text,integer) TO service_role;
REVOKE EXECUTE ON FUNCTION public.open_ro_detail(text,integer) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.open_ro_detail(text,integer) TO service_role;
REVOKE EXECUTE ON FUNCTION public.openclaw_queue_health(integer) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.openclaw_queue_health(integer) TO service_role;
REVOKE EXECUTE ON FUNCTION public.part_lookup_context(text,integer) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.part_lookup_context(text,integer) TO service_role;
REVOKE EXECUTE ON FUNCTION public.part_sales_summary(text,date,date) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.part_sales_summary(text,date,date) TO service_role;
REVOKE EXECUTE ON FUNCTION public.service_recommendation_followups(text,integer,integer) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.service_recommendation_followups(text,integer,integer) TO service_role;
REVOKE EXECUTE ON FUNCTION public.service_recommendations_due(text,integer,integer) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.service_recommendations_due(text,integer,integer) TO service_role;

