-- Insert Mercury accessory products into motor_options
INSERT INTO public.motor_options (name, description, short_description, category, base_price, part_number, image_url, features, is_taxable, is_active, display_order) VALUES

-- SmartCraft Connect Mobile (electronics - hero item)
('SmartCraft Connect Mobile', 
 'Plug-and-play module that streams live engine performance data to your smartphone via Bluetooth. Monitor fuel burn, battery voltage, GPS range, and more. Compatible with Mercury outboards 40hp+ (2004+) and 25-30hp (2022+).', 
 'Stream live engine data to your smartphone',
 'electronics', 
 325.00, 
 '8M0173128', 
 'https://eutsoqdpjurknjsshxes.supabase.co/storage/v1/object/public/motor-images/accessories/smartcraft-connect-mobile.png',
 '["Real-time engine monitoring", "Fuel burn & range tracking", "Battery voltage alerts", "GPS range rings", "Maintenance reminders", "iOS & Android compatible"]'::jsonb,
 true, true, 1),

-- 100-Hour Service Kits
('100-Hour Service Kit (Under 25HP)', 
 'Complete 100-hour maintenance kit for Mercury outboards under 25HP. Includes oil filter, fuel filter, and gear lube for essential engine maintenance.',
 'Oil filter, fuel filter, gear lube',
 'maintenance', 
 95.00, 
 '8M0151469',
 'https://eutsoqdpjurknjsshxes.supabase.co/storage/v1/object/public/motor-images/accessories/maintenance-kit-generic.jpg',
 '["Oil filter", "Fuel filter", "Gear lube", "Genuine Mercury parts"]'::jsonb,
 true, true, 10),

('100-Hour Service Kit (40-60HP)', 
 'Complete 100-hour maintenance kit for Mercury outboards 40-60HP. Includes oil filter, fuel filter, and gear lube for essential engine maintenance.',
 'Oil filter, fuel filter, gear lube',
 'maintenance', 
 80.00, 
 '8M0232733',
 'https://eutsoqdpjurknjsshxes.supabase.co/storage/v1/object/public/motor-images/accessories/maintenance-kit-generic.jpg',
 '["Oil filter", "Fuel filter", "Gear lube", "Genuine Mercury parts"]'::jsonb,
 true, true, 11),

('100-Hour Service Kit (75-115HP)', 
 'Complete 100-hour maintenance kit for Mercury 2.1L outboards 75-115HP. Includes spark plugs, fuel filter, and gear lube.',
 'Spark plugs, fuel filter, gear lube',
 'maintenance', 
 55.00, 
 '8M0097854',
 'https://eutsoqdpjurknjsshxes.supabase.co/storage/v1/object/public/motor-images/accessories/maintenance-kit-generic.jpg',
 '["Spark plugs", "Fuel filter", "Gear lube", "Genuine Mercury parts"]'::jsonb,
 true, true, 12),

('100-Hour Service Kit (150HP)', 
 'Complete 100-hour maintenance kit for Mercury 150HP outboards. Includes filter kit and spark plugs for essential engine maintenance.',
 'Filter kit, spark plugs',
 'maintenance', 
 65.00, 
 '8M0094232',
 'https://eutsoqdpjurknjsshxes.supabase.co/storage/v1/object/public/motor-images/accessories/maintenance-kit-generic.jpg',
 '["Filter kit", "Spark plugs", "Genuine Mercury parts"]'::jsonb,
 true, true, 13),

('100-Hour Service Kit (175-300HP)', 
 'Complete 100-hour maintenance kit for Mercury V6/V8 outboards 175-300HP. Includes complete filter set for essential engine maintenance.',
 'Complete filter set',
 'maintenance', 
 105.00, 
 '8M0149929',
 'https://eutsoqdpjurknjsshxes.supabase.co/storage/v1/object/public/motor-images/accessories/maintenance-kit-generic.jpg',
 '["Complete filter set", "Genuine Mercury parts"]'::jsonb,
 true, true, 14),

-- 300-Hour Service Kits
('300-Hour Service Kit (40-60HP)', 
 'Comprehensive 300-hour service kit for Mercury 40-60HP outboards. Includes all 100-hour items plus impeller and thermostat.',
 'All 100-hr items + impeller, thermostat',
 'maintenance', 
 340.00, 
 '8M0090559',
 'https://eutsoqdpjurknjsshxes.supabase.co/storage/v1/object/public/motor-images/accessories/maintenance-kit-generic.jpg',
 '["All 100-hour items", "Water pump impeller", "Thermostat", "Genuine Mercury parts"]'::jsonb,
 true, true, 20),

('300-Hour Service Kit (75-115HP)', 
 'Comprehensive 300-hour service kit for Mercury 2.1L 75-115HP outboards. Complete service package.',
 'Complete service package',
 'maintenance', 
 440.00, 
 '8M0097855',
 'https://eutsoqdpjurknjsshxes.supabase.co/storage/v1/object/public/motor-images/accessories/maintenance-kit-generic.jpg',
 '["Complete filter set", "Water pump impeller", "Thermostat", "Spark plugs", "Genuine Mercury parts"]'::jsonb,
 true, true, 21),

('300-Hour Service Kit (150HP)', 
 'Comprehensive 300-hour service kit for Mercury 150HP outboards. Full 300-hour maintenance package.',
 'Full 300-hr maintenance',
 'maintenance', 
 510.00, 
 '8M0094233',
 'https://eutsoqdpjurknjsshxes.supabase.co/storage/v1/object/public/motor-images/accessories/maintenance-kit-generic.jpg',
 '["Complete filter set", "Water pump impeller", "Thermostat", "Spark plugs", "Genuine Mercury parts"]'::jsonb,
 true, true, 22),

('300-Hour Service Kit (175-225HP)', 
 'Comprehensive 300-hour service kit for Mercury V6 175-225HP outboards. Includes all filters, impeller, and belt.',
 'All filters + impeller + belt',
 'maintenance', 
 500.00, 
 '8M0149930',
 'https://eutsoqdpjurknjsshxes.supabase.co/storage/v1/object/public/motor-images/accessories/maintenance-kit-generic.jpg',
 '["Complete filter set", "Water pump impeller", "Drive belt", "Thermostat", "Genuine Mercury parts"]'::jsonb,
 true, true, 23),

('300-Hour Service Kit (250-300HP)', 
 'Premium 300-hour service kit for Mercury V8 250-300HP outboards. Complete service package with all components.',
 'Premium complete kit',
 'maintenance', 
 700.00, 
 '8M0149931',
 'https://eutsoqdpjurknjsshxes.supabase.co/storage/v1/object/public/motor-images/accessories/maintenance-kit-generic.jpg',
 '["Complete filter set", "Water pump impeller", "Drive belt", "Thermostat", "Spark plugs", "Genuine Mercury parts"]'::jsonb,
 true, true, 24),

-- Oil Change Kits
('Oil Change Kit (40-60HP)', 
 'Oil change kit for Mercury 40-60HP outboards. Includes 25W-40 oil and filter.',
 '25W-40 oil & filter',
 'maintenance', 
 90.00, 
 '8M0081916',
 'https://eutsoqdpjurknjsshxes.supabase.co/storage/v1/object/public/motor-images/accessories/maintenance-kit-generic.jpg',
 '["25W-40 Marine oil", "Oil filter", "Drain plug gasket", "Genuine Mercury parts"]'::jsonb,
 true, true, 30),

('Oil Change Kit (75-115HP)', 
 'Oil change kit for Mercury 2.1L 75-115HP outboards. Includes 10W-30 synthetic oil and filter.',
 '10W-30 synthetic oil & filter',
 'maintenance', 
 125.00, 
 '8M0107510',
 'https://eutsoqdpjurknjsshxes.supabase.co/storage/v1/object/public/motor-images/accessories/maintenance-kit-generic.jpg',
 '["10W-30 Synthetic oil", "Oil filter", "Drain plug gasket", "Genuine Mercury parts"]'::jsonb,
 true, true, 31),

('Oil Change Kit (150HP)', 
 'Oil change kit for Mercury 150HP outboards. Includes 10W-30 synthetic oil and filter.',
 '10W-30 synthetic oil & filter',
 'maintenance', 
 140.00, 
 '8M0188357',
 'https://eutsoqdpjurknjsshxes.supabase.co/storage/v1/object/public/motor-images/accessories/maintenance-kit-generic.jpg',
 '["10W-30 Synthetic oil", "Oil filter", "Drain plug gasket", "Genuine Mercury parts"]'::jsonb,
 true, true, 32),

('Oil Change Kit (175-225HP)', 
 'Oil change kit for Mercury V6 175-225HP outboards. Includes 10W-30 synthetic oil and filter.',
 '10W-30 synthetic oil & filter',
 'maintenance', 
 180.00, 
 '8M0187621',
 'https://eutsoqdpjurknjsshxes.supabase.co/storage/v1/object/public/motor-images/accessories/maintenance-kit-generic.jpg',
 '["10W-30 Synthetic oil", "Oil filter", "Drain plug gasket", "Genuine Mercury parts"]'::jsonb,
 true, true, 33),

('Oil Change Kit (250-300HP)', 
 'Oil change kit for Mercury V8 250-300HP outboards. Includes 10W-30 synthetic oil and filter.',
 '10W-30 synthetic oil & filter',
 'maintenance', 
 215.00, 
 '8M0187622',
 'https://eutsoqdpjurknjsshxes.supabase.co/storage/v1/object/public/motor-images/accessories/maintenance-kit-generic.jpg',
 '["10W-30 Synthetic oil", "Oil filter", "Drain plug gasket", "Genuine Mercury parts"]'::jsonb,
 true, true, 34)

ON CONFLICT (part_number) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  short_description = EXCLUDED.short_description,
  image_url = EXCLUDED.image_url,
  base_price = EXCLUDED.base_price,
  features = EXCLUDED.features,
  updated_at = now();