// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';


const runtimeEnv = (import.meta as any).env ?? {};
const nodeEnv = typeof process !== 'undefined' ? process.env : {};

const SUPABASE_URL =
  runtimeEnv.VITE_SUPABASE_URL ||
  nodeEnv.VITE_SUPABASE_URL ||
  "https://eutsoqdpjurknjsshxes.supabase.co";
const SUPABASE_PUBLISHABLE_KEY =
  runtimeEnv.VITE_SUPABASE_PUBLISHABLE_KEY ||
  nodeEnv.VITE_SUPABASE_PUBLISHABLE_KEY ||
  nodeEnv.SUPABASE_PUBLISHABLE_KEY ||
  "";

// In-memory storage fallback
const __memoryStore: Record<string, string> = {};
const memoryStorage = {
  getItem: (key: string) => (__memoryStore[key] ?? null),
  setItem: (key: string, value: string) => { __memoryStore[key] = value },
  removeItem: (key: string) => { delete __memoryStore[key] },
};

// Prefer persistent localStorage when available (prevents login loops on refresh)
const _win = typeof globalThis !== 'undefined' ? (globalThis as any) : undefined;

const supportsLocalStorage = !!_win && (() => {
  try {
    const k = '__supabase_test__';
    _win.localStorage.setItem(k, '1');
    _win.localStorage.removeItem(k);
    return true;
  } catch {
    return false;
  }
})();

const safeStorage: Pick<Storage, 'getItem' | 'setItem' | 'removeItem'> = supportsLocalStorage ? _win!.localStorage : memoryStorage;

// Session ID key for anonymous user tracking (used by RLS policies)
const SESSION_ID_KEY = 'chat_session_id';

// Get or create a cryptographically secure session ID for anonymous users
function getOrCreateSessionId(): string {
  if (!_win) return '';
  
  try {
    let sessionId = safeStorage.getItem(SESSION_ID_KEY);
    if (!sessionId) {
      const array = new Uint8Array(16);
      crypto.getRandomValues(array);
      sessionId = `voice_${Array.from(array, b => b.toString(16).padStart(2, '0')).join('')}`;
      safeStorage.setItem(SESSION_ID_KEY, sessionId);
    }
    return sessionId;
  } catch {
    return '';
  }
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: safeStorage,
    persistSession: true,
    autoRefreshToken: true,
    flowType: 'pkce',
    detectSessionInUrl: true,
  },
  global: {
    headers: {
      // Pass session ID header for RLS policy validation (voice_sessions, customer_quotes, etc.)
      'x-session-id': getOrCreateSessionId(),
    },
  },
});
