// AUTO-GENERATED by scripts/generate-canonical-pricing.mjs
// Source: public/pricing-reference.md (last_updated: 2026-07-12)
// Do not edit by hand. Re-run `npm run generate:canonical-pricing`.

export interface CanonicalSku {
  partNo: string;
  model: string;
  family: 'FourStroke' | 'ProXS' | 'SeaPro' | 'Verado' | string;
  hp: number;
  dealer: number;
  msrp: number;
  status: string;
  slug: string;
}

export interface CanonicalRange {
  count: number;
  dealerMin: number;
  dealerMax: number;
  msrpMin: number;
  msrpMax: number;
}

export const CANONICAL_LAST_UPDATED = "2026-07-12";

export const CANONICAL_SKUS: CanonicalSku[] = [
  {
    "partNo": "1F02201KK",
    "model": "2.5MH FourStroke",
    "family": "FourStroke",
    "hp": 2.5,
    "dealer": 1298,
    "msrp": 1385,
    "status": "In stock",
    "slug": "2-5mh-fourstroke"
  },
  {
    "partNo": "1F03201KK",
    "model": "3.5MH FourStroke",
    "family": "FourStroke",
    "hp": 3.5,
    "dealer": 1557,
    "msrp": 1660,
    "status": "Available to order",
    "slug": "3-5mh-fourstroke"
  },
  {
    "partNo": "1F03211KK",
    "model": "3.5MLH FourStroke",
    "family": "FourStroke",
    "hp": 3.5,
    "dealer": 1590,
    "msrp": 1695,
    "status": "Available to order",
    "slug": "3-5mlh-fourstroke"
  },
  {
    "partNo": "1F04201KK",
    "model": "4MH FourStroke",
    "family": "FourStroke",
    "hp": 4,
    "dealer": 1854,
    "msrp": 1975,
    "status": "Available to order",
    "slug": "4mh-fourstroke"
  },
  {
    "partNo": "1F04211KK",
    "model": "4MLH FourStroke",
    "family": "FourStroke",
    "hp": 4,
    "dealer": 1892,
    "msrp": 2015,
    "status": "Available to order",
    "slug": "4mlh-fourstroke"
  },
  {
    "partNo": "1F05216KK",
    "model": "5MLHA Sail Power FourStroke",
    "family": "FourStroke",
    "hp": 5,
    "dealer": 2096,
    "msrp": 2235,
    "status": "Available to order",
    "slug": "5mlha-sail-power-fourstroke"
  },
  {
    "partNo": "1F05221KK",
    "model": "5MXLH FourStroke",
    "family": "FourStroke",
    "hp": 5,
    "dealer": 2134,
    "msrp": 2275,
    "status": "Available to order",
    "slug": "5mxlh-fourstroke"
  },
  {
    "partNo": "1FX5201KK",
    "model": "5MH FourStroke",
    "family": "FourStroke",
    "hp": 5,
    "dealer": 2057,
    "msrp": 2190,
    "status": "Available to order",
    "slug": "5mh-fourstroke"
  },
  {
    "partNo": "1FX6201KK",
    "model": "6MH FourStroke",
    "family": "FourStroke",
    "hp": 6,
    "dealer": 2129,
    "msrp": 2270,
    "status": "In stock",
    "slug": "6mh-fourstroke"
  },
  {
    "partNo": "1FX6211KK",
    "model": "6MLH FourStroke",
    "family": "FourStroke",
    "hp": 6,
    "dealer": 2162,
    "msrp": 2305,
    "status": "Available to order",
    "slug": "6mlh-fourstroke"
  },
  {
    "partNo": "1A08201LK",
    "model": "8MH FourStroke",
    "family": "FourStroke",
    "hp": 8,
    "dealer": 3097,
    "msrp": 3300,
    "status": "Available to order",
    "slug": "8mh-fourstroke"
  },
  {
    "partNo": "1A08211LK",
    "model": "8MLH FourStroke",
    "family": "FourStroke",
    "hp": 8,
    "dealer": 3135,
    "msrp": 3340,
    "status": "Available to order",
    "slug": "8mlh-fourstroke"
  },
  {
    "partNo": "1A08301LK",
    "model": "8EH FourStroke",
    "family": "FourStroke",
    "hp": 8,
    "dealer": 3410,
    "msrp": 3635,
    "status": "Available to order",
    "slug": "8eh-fourstroke"
  },
  {
    "partNo": "1A08311LK",
    "model": "8ELH FourStroke",
    "family": "FourStroke",
    "hp": 8,
    "dealer": 3449,
    "msrp": 3675,
    "status": "Available to order",
    "slug": "8elh-fourstroke"
  },
  {
    "partNo": "1A10201LK",
    "model": "9.9MH FourStroke",
    "family": "FourStroke",
    "hp": 9.9,
    "dealer": 2999,
    "msrp": 3860,
    "status": "In stock",
    "slug": "9-9mh-fourstroke"
  },
  {
    "partNo": "1A10211LK",
    "model": "9.9MLH FourStroke",
    "family": "FourStroke",
    "hp": 9.9,
    "dealer": 2999,
    "msrp": 3910,
    "status": "In stock",
    "slug": "9-9mlh-fourstroke"
  },
  {
    "partNo": "1A10251LK",
    "model": "9.9MLH Command Thrust FourStroke",
    "family": "FourStroke",
    "hp": 9.9,
    "dealer": 3971,
    "msrp": 4230,
    "status": "Available to order",
    "slug": "9-9mlh-ct-fourstroke"
  },
  {
    "partNo": "1A10301LK",
    "model": "9.9EH FourStroke",
    "family": "FourStroke",
    "hp": 9.9,
    "dealer": 3299,
    "msrp": 4215,
    "status": "Available to order",
    "slug": "9-9eh-fourstroke"
  },
  {
    "partNo": "1A10311LK",
    "model": "9.9ELH FourStroke",
    "family": "FourStroke",
    "hp": 9.9,
    "dealer": 3399,
    "msrp": 4420,
    "status": "In stock",
    "slug": "9-9elh-fourstroke"
  },
  {
    "partNo": "1A10351LK",
    "model": "9.9ELH Command Thrust FourStroke",
    "family": "FourStroke",
    "hp": 9.9,
    "dealer": 4477,
    "msrp": 4770,
    "status": "Available to order",
    "slug": "9-9elh-ct-fourstroke"
  },
  {
    "partNo": "1A10361LK",
    "model": "9.9EXLH Command Thrust FourStroke",
    "family": "FourStroke",
    "hp": 9.9,
    "dealer": 4554,
    "msrp": 4850,
    "status": "Available to order",
    "slug": "9-9exlh-ct-fourstroke"
  },
  {
    "partNo": "1A10451LK",
    "model": "9.9ELHPT Command Thrust ProKicker EFI FourStroke",
    "family": "FourStroke",
    "hp": 9.9,
    "dealer": 5099,
    "msrp": 5430,
    "status": "Available to order",
    "slug": "9-9elhpt-ct-prokicker-efi-fourstroke"
  },
  {
    "partNo": "1A10452LK",
    "model": "9.9ELPT Command Thrust ProKicker EFI FourStroke",
    "family": "FourStroke",
    "hp": 9.9,
    "dealer": 5000,
    "msrp": 5325,
    "status": "Available to order",
    "slug": "9-9elpt-ct-prokicker-efi-fourstroke"
  },
  {
    "partNo": "1A10461LK",
    "model": "9.9EXLHPT Command Thrust ProKicker EFI FourStroke",
    "family": "FourStroke",
    "hp": 9.9,
    "dealer": 5198,
    "msrp": 5540,
    "status": "Available to order",
    "slug": "9-9exlhpt-ct-prokicker-efi-fourstroke"
  },
  {
    "partNo": "1A10462LK",
    "model": "9.9EXLPT Command Thrust ProKicker EFI FourStroke",
    "family": "FourStroke",
    "hp": 9.9,
    "dealer": 5082,
    "msrp": 5415,
    "status": "Available to order",
    "slug": "9-9exlpt-ct-prokicker-efi-fourstroke"
  },
  {
    "partNo": "1A15201LK",
    "model": "15MH FourStroke",
    "family": "FourStroke",
    "hp": 15,
    "dealer": 3971,
    "msrp": 4230,
    "status": "Available to order",
    "slug": "15mh-fourstroke"
  },
  {
    "partNo": "1A15211LK",
    "model": "15MLH FourStroke",
    "family": "FourStroke",
    "hp": 15,
    "dealer": 4021,
    "msrp": 4285,
    "status": "Available to order",
    "slug": "15mlh-fourstroke"
  },
  {
    "partNo": "1A15301LK",
    "model": "15EH FourStroke",
    "family": "FourStroke",
    "hp": 15,
    "dealer": 4323,
    "msrp": 4605,
    "status": "Available to order",
    "slug": "15eh-fourstroke"
  },
  {
    "partNo": "1A15311LK",
    "model": "15ELH FourStroke",
    "family": "FourStroke",
    "hp": 15,
    "dealer": 4378,
    "msrp": 4665,
    "status": "Available to order",
    "slug": "15elh-fourstroke"
  },
  {
    "partNo": "1A15451BK",
    "model": "15ELHPT ProKicker FourStroke",
    "family": "FourStroke",
    "hp": 15,
    "dealer": 5599,
    "msrp": 5965,
    "status": "Available to order",
    "slug": "15elhpt-prokicker-fourstroke"
  },
  {
    "partNo": "1A15452BK",
    "model": "15ELPT ProKicker FourStroke",
    "family": "FourStroke",
    "hp": 15,
    "dealer": 5500,
    "msrp": 5860,
    "status": "Available to order",
    "slug": "15elpt-prokicker-fourstroke"
  },
  {
    "partNo": "1A15461BK",
    "model": "15EXLHPT ProKicker FourStroke",
    "family": "FourStroke",
    "hp": 15,
    "dealer": 5709,
    "msrp": 6085,
    "status": "Available to order",
    "slug": "15exlhpt-prokicker-fourstroke"
  },
  {
    "partNo": "1A15462BK",
    "model": "15EXLPT ProKicker FourStroke",
    "family": "FourStroke",
    "hp": 15,
    "dealer": 5594,
    "msrp": 5960,
    "status": "Available to order",
    "slug": "15exlpt-prokicker-fourstroke"
  },
  {
    "partNo": "1A20201LK",
    "model": "20MH FourStroke",
    "family": "FourStroke",
    "hp": 20,
    "dealer": 4334,
    "msrp": 4620,
    "status": "Available to order",
    "slug": "20mh-fourstroke"
  },
  {
    "partNo": "1A20211LK",
    "model": "20MLH FourStroke",
    "family": "FourStroke",
    "hp": 20,
    "dealer": 4373,
    "msrp": 4660,
    "status": "Available to order",
    "slug": "20mlh-fourstroke"
  },
  {
    "partNo": "1A20301LK",
    "model": "20EH FourStroke",
    "family": "FourStroke",
    "hp": 20,
    "dealer": 4802,
    "msrp": 5115,
    "status": "In stock",
    "slug": "20eh-fourstroke"
  },
  {
    "partNo": "1A20311LK",
    "model": "20ELH FourStroke",
    "family": "FourStroke",
    "hp": 20,
    "dealer": 4873,
    "msrp": 5190,
    "status": "In stock",
    "slug": "20elh-fourstroke"
  },
  {
    "partNo": "1A20411LK",
    "model": "20ELHPT FourStroke",
    "family": "FourStroke",
    "hp": 20,
    "dealer": 5528,
    "msrp": 5890,
    "status": "In stock",
    "slug": "20elhpt-fourstroke"
  },
  {
    "partNo": "1A25213BK",
    "model": "25MLH FourStroke",
    "family": "FourStroke",
    "hp": 25,
    "dealer": 5093,
    "msrp": 5425,
    "status": "Available to order",
    "slug": "25mlh-fourstroke"
  },
  {
    "partNo": "1A25411BK",
    "model": "25ELHPT FourStroke",
    "family": "FourStroke",
    "hp": 25,
    "dealer": 6265,
    "msrp": 6675,
    "status": "Available to order",
    "slug": "25elhpt-fourstroke"
  },
  {
    "partNo": "1A25413BK",
    "model": "25ELPT FourStroke",
    "family": "FourStroke",
    "hp": 25,
    "dealer": 6144,
    "msrp": 6545,
    "status": "Available to order",
    "slug": "25elpt-fourstroke"
  },
  {
    "partNo": "1A30411BK",
    "model": "30ELHPT FourStroke",
    "family": "FourStroke",
    "hp": 30,
    "dealer": 7926,
    "msrp": 8445,
    "status": "Available to order",
    "slug": "30elhpt-fourstroke"
  },
  {
    "partNo": "1A30413BK",
    "model": "30ELPT FourStroke",
    "family": "FourStroke",
    "hp": 30,
    "dealer": 7805,
    "msrp": 8315,
    "status": "Available to order",
    "slug": "30elpt-fourstroke"
  },
  {
    "partNo": "1F40413GZ",
    "model": "40ELPT FourStroke",
    "family": "FourStroke",
    "hp": 40,
    "dealer": 9438,
    "msrp": 10515,
    "status": "Available to order",
    "slug": "40elpt-fourstroke"
  },
  {
    "partNo": "1F4041TJZ",
    "model": "40ELHPT FourStroke",
    "family": "FourStroke",
    "hp": 40,
    "dealer": 9955,
    "msrp": 11090,
    "status": "Available to order",
    "slug": "40elhpt-fourstroke"
  },
  {
    "partNo": "1F41453GZ",
    "model": "40ELPT Command Thrust FourStroke",
    "family": "FourStroke",
    "hp": 40,
    "dealer": 9801,
    "msrp": 10920,
    "status": "Available to order",
    "slug": "40elpt-ct-fourstroke"
  },
  {
    "partNo": "1F51413GZ",
    "model": "50ELPT FourStroke",
    "family": "FourStroke",
    "hp": 50,
    "dealer": 10599,
    "msrp": 11805,
    "status": "Available to order",
    "slug": "50elpt-fourstroke"
  },
  {
    "partNo": "1F51453GZ",
    "model": "50ELPT Command Thrust FourStroke",
    "family": "FourStroke",
    "hp": 50,
    "dealer": 11017,
    "msrp": 12275,
    "status": "Available to order",
    "slug": "50elpt-ct-fourstroke"
  },
  {
    "partNo": "1F5145TJZ",
    "model": "50ELHPT FourStroke",
    "family": "FourStroke",
    "hp": 50,
    "dealer": 11484,
    "msrp": 12795,
    "status": "Available to order",
    "slug": "50elhpt-fourstroke"
  },
  {
    "partNo": "1F60413GZ",
    "model": "60ELPT FourStroke",
    "family": "FourStroke",
    "hp": 60,
    "dealer": 12040,
    "msrp": 13415,
    "status": "In stock",
    "slug": "60elpt-fourstroke"
  },
  {
    "partNo": "1F6041TJZ",
    "model": "60ELHPT FourStroke Tiller",
    "family": "FourStroke",
    "hp": 60,
    "dealer": 12700,
    "msrp": 14150,
    "status": "Available to order",
    "slug": "60elhpt-fourstroke-tiller"
  },
  {
    "partNo": "1F60453GZ",
    "model": "60ELPT Command Thrust FourStroke",
    "family": "FourStroke",
    "hp": 60,
    "dealer": 12342,
    "msrp": 13750,
    "status": "In stock",
    "slug": "60elpt-ct-fourstroke"
  },
  {
    "partNo": "1F6045TJZ",
    "model": "60ELHPT Command Thrust FourStroke Tiller",
    "family": "FourStroke",
    "hp": 60,
    "dealer": 13057,
    "msrp": 14545,
    "status": "Available to order",
    "slug": "60elhpt-ct-fourstroke-tiller"
  },
  {
    "partNo": "1F60463GZ",
    "model": "60EXLPT FourStroke",
    "family": "FourStroke",
    "hp": 60,
    "dealer": 12689,
    "msrp": 14135,
    "status": "Available to order",
    "slug": "60exlpt-fourstroke"
  },
  {
    "partNo": "1F754132D",
    "model": "75ELPT FourStroke",
    "family": "FourStroke",
    "hp": 75,
    "dealer": 14476,
    "msrp": 16125,
    "status": "Available to order",
    "slug": "75elpt-fourstroke"
  },
  {
    "partNo": "1F904132D",
    "model": "90ELPT FourStroke",
    "family": "FourStroke",
    "hp": 90,
    "dealer": 14960,
    "msrp": 16665,
    "status": "In stock",
    "slug": "90elpt-fourstroke"
  },
  {
    "partNo": "1F904532D",
    "model": "90ELPT Command Thrust FourStroke",
    "family": "FourStroke",
    "hp": 90,
    "dealer": 15428,
    "msrp": 17185,
    "status": "Available to order",
    "slug": "90elpt-ct-fourstroke"
  },
  {
    "partNo": "1F904632D",
    "model": "90EXLPT FourStroke",
    "family": "FourStroke",
    "hp": 90,
    "dealer": 15477,
    "msrp": 17240,
    "status": "Available to order",
    "slug": "90exlpt-fourstroke"
  },
  {
    "partNo": "1115F132D",
    "model": "115ELPT FourStroke",
    "family": "FourStroke",
    "hp": 115,
    "dealer": 17083,
    "msrp": 19030,
    "status": "In stock",
    "slug": "115elpt-fourstroke"
  },
  {
    "partNo": "1115F232D",
    "model": "115EXLPT FourStroke",
    "family": "FourStroke",
    "hp": 115,
    "dealer": 17441,
    "msrp": 19430,
    "status": "Available to order",
    "slug": "115exlpt-fourstroke"
  },
  {
    "partNo": "1115F532D",
    "model": "115ELPT Command Thrust FourStroke",
    "family": "FourStroke",
    "hp": 115,
    "dealer": 17540,
    "msrp": 19540,
    "status": "Available to order",
    "slug": "115elpt-ct-fourstroke"
  },
  {
    "partNo": "1115F632D",
    "model": "115EXLPT Command Thrust FourStroke",
    "family": "FourStroke",
    "hp": 115,
    "dealer": 17892,
    "msrp": 19930,
    "status": "Available to order",
    "slug": "115exlpt-ct-fourstroke"
  },
  {
    "partNo": "1150F13ED",
    "model": "150L FourStroke",
    "family": "FourStroke",
    "hp": 150,
    "dealer": 22242,
    "msrp": 24780,
    "status": "Available to order",
    "slug": "150l-fourstroke"
  },
  {
    "partNo": "1150F23ED",
    "model": "150XL FourStroke",
    "family": "FourStroke",
    "hp": 150,
    "dealer": 22363,
    "msrp": 24915,
    "status": "Available to order",
    "slug": "150xl-fourstroke"
  },
  {
    "partNo": "11750005A",
    "model": "175L FourStroke",
    "family": "FourStroke",
    "hp": 175,
    "dealer": 27544,
    "msrp": 30685,
    "status": "Available to order",
    "slug": "175l-fourstroke"
  },
  {
    "partNo": "11750006A",
    "model": "175XL FourStroke",
    "family": "FourStroke",
    "hp": 175,
    "dealer": 27676,
    "msrp": 30830,
    "status": "Available to order",
    "slug": "175xl-fourstroke"
  },
  {
    "partNo": "12000005A",
    "model": "200L FourStroke",
    "family": "FourStroke",
    "hp": 200,
    "dealer": 29623,
    "msrp": 33000,
    "status": "Available to order",
    "slug": "200l-fourstroke"
  },
  {
    "partNo": "12000009A",
    "model": "200XL FourStroke",
    "family": "FourStroke",
    "hp": 200,
    "dealer": 27858,
    "msrp": 31035,
    "status": "Available to order",
    "slug": "200xl-fourstroke"
  },
  {
    "partNo": "12250001A",
    "model": "225L FourStroke",
    "family": "FourStroke",
    "hp": 225,
    "dealer": 33275,
    "msrp": 37070,
    "status": "Available to order",
    "slug": "225l-fourstroke"
  },
  {
    "partNo": "12250013A",
    "model": "225XL FourStroke",
    "family": "FourStroke",
    "hp": 225,
    "dealer": 35343,
    "msrp": 39375,
    "status": "Available to order",
    "slug": "225xl-fourstroke"
  },
  {
    "partNo": "12250025A",
    "model": "225XXL FourStroke",
    "family": "FourStroke",
    "hp": 225,
    "dealer": 36053,
    "msrp": 40165,
    "status": "Available to order",
    "slug": "225xxl-fourstroke"
  },
  {
    "partNo": "12250029A",
    "model": "225CXXL FourStroke",
    "family": "FourStroke",
    "hp": 225,
    "dealer": 36801,
    "msrp": 40995,
    "status": "Available to order",
    "slug": "225cxxl-fourstroke"
  },
  {
    "partNo": "12500005A",
    "model": "250L FourStroke",
    "family": "FourStroke",
    "hp": 250,
    "dealer": 37213,
    "msrp": 41455,
    "status": "Available to order",
    "slug": "250l-fourstroke"
  },
  {
    "partNo": "12500013A",
    "model": "250XL FourStroke",
    "family": "FourStroke",
    "hp": 250,
    "dealer": 36619,
    "msrp": 40795,
    "status": "Available to order",
    "slug": "250xl-fourstroke"
  },
  {
    "partNo": "12500025A",
    "model": "250XXL FourStroke",
    "family": "FourStroke",
    "hp": 250,
    "dealer": 37466,
    "msrp": 41740,
    "status": "Available to order",
    "slug": "250xxl-fourstroke"
  },
  {
    "partNo": "12500087A",
    "model": "250CXXL FourStroke",
    "family": "FourStroke",
    "hp": 250,
    "dealer": 36080,
    "msrp": 40195,
    "status": "Available to order",
    "slug": "250cxxl-fourstroke"
  },
  {
    "partNo": "13000002A",
    "model": "300L FourStroke",
    "family": "FourStroke",
    "hp": 300,
    "dealer": 36421,
    "msrp": 40575,
    "status": "Available to order",
    "slug": "300l-fourstroke"
  },
  {
    "partNo": "13000006A",
    "model": "300L FourStroke DTS",
    "family": "FourStroke",
    "hp": 300,
    "dealer": 38412,
    "msrp": 42795,
    "status": "Available to order",
    "slug": "300l-fourstroke-dts"
  },
  {
    "partNo": "13000010A",
    "model": "300XL FourStroke",
    "family": "FourStroke",
    "hp": 300,
    "dealer": 36531,
    "msrp": 40695,
    "status": "Available to order",
    "slug": "300xl-fourstroke"
  },
  {
    "partNo": "13000014A",
    "model": "300XL FourStroke DTS",
    "family": "FourStroke",
    "hp": 300,
    "dealer": 38539,
    "msrp": 42935,
    "status": "Available to order",
    "slug": "300xl-fourstroke-dts"
  },
  {
    "partNo": "1117F131D",
    "model": "115ELPT ProXS",
    "family": "ProXS",
    "hp": 115,
    "dealer": 17490,
    "msrp": 19485,
    "status": "In stock",
    "slug": "115elpt-pro-xs"
  },
  {
    "partNo": "1117F231D",
    "model": "115EXLPT ProXS",
    "family": "ProXS",
    "hp": 115,
    "dealer": 17842,
    "msrp": 19875,
    "status": "In stock",
    "slug": "115exlpt-pro-xs"
  },
  {
    "partNo": "1117F531D",
    "model": "115ELPT Pro XS Command Thrust",
    "family": "ProXS",
    "hp": 115,
    "dealer": 17941,
    "msrp": 19985,
    "status": "Available to order",
    "slug": "115elpt-pro-xs-ct"
  },
  {
    "partNo": "1117F631D",
    "model": "115EXLPT Pro XS Command Thrust",
    "family": "ProXS",
    "hp": 115,
    "dealer": 18299,
    "msrp": 20385,
    "status": "Available to order",
    "slug": "115exlpt-pro-xs-ct"
  },
  {
    "partNo": "1152F131D",
    "model": "150ELPT ProXS",
    "family": "ProXS",
    "hp": 150,
    "dealer": 24349,
    "msrp": 27125,
    "status": "In stock",
    "slug": "150elpt-pro-xs"
  },
  {
    "partNo": "1152F231D",
    "model": "150EXLPT ProXS",
    "family": "ProXS",
    "hp": 150,
    "dealer": 24475,
    "msrp": 27265,
    "status": "In stock",
    "slug": "150exlpt-pro-xs"
  },
  {
    "partNo": "11750001A",
    "model": "175ELPT ProXS",
    "family": "ProXS",
    "hp": 175,
    "dealer": 27891,
    "msrp": 31070,
    "status": "Available to order",
    "slug": "175elpt-pro-xs"
  },
  {
    "partNo": "11750002A",
    "model": "175EXLPT ProXS",
    "family": "ProXS",
    "hp": 175,
    "dealer": 28287,
    "msrp": 31510,
    "status": "Available to order",
    "slug": "175exlpt-pro-xs"
  },
  {
    "partNo": "12000035A",
    "model": "200ELPT ProXS DTS",
    "family": "ProXS",
    "hp": 200,
    "dealer": 29992,
    "msrp": 33410,
    "status": "In stock",
    "slug": "200elpt-pro-xs-dts"
  },
  {
    "partNo": "12000039A",
    "model": "200ELPT ProXS",
    "family": "ProXS",
    "hp": 200,
    "dealer": 28122,
    "msrp": 31330,
    "status": "In stock",
    "slug": "200elpt-pro-xs"
  },
  {
    "partNo": "12000040A",
    "model": "200EXLPT ProXS DTS",
    "family": "ProXS",
    "hp": 200,
    "dealer": 30399,
    "msrp": 33865,
    "status": "Available to order",
    "slug": "200exlpt-pro-xs-dts"
  },
  {
    "partNo": "12250033A",
    "model": "225ELPT ProXS",
    "family": "ProXS",
    "hp": 225,
    "dealer": 34029,
    "msrp": 37910,
    "status": "Available to order",
    "slug": "225elpt-pro-xs"
  },
  {
    "partNo": "12250055A",
    "model": "225EXLPT ProXS",
    "family": "ProXS",
    "hp": 225,
    "dealer": 36300,
    "msrp": 40440,
    "status": "Available to order",
    "slug": "225exlpt-pro-xs"
  },
  {
    "partNo": "12500033A",
    "model": "250ELPT ProXS",
    "family": "ProXS",
    "hp": 250,
    "dealer": 34848,
    "msrp": 38820,
    "status": "In stock",
    "slug": "250elpt-pro-xs"
  },
  {
    "partNo": "12500034A",
    "model": "250EXLPT ProXS",
    "family": "ProXS",
    "hp": 250,
    "dealer": 35646,
    "msrp": 39710,
    "status": "Available to order",
    "slug": "250exlpt-pro-xs"
  },
  {
    "partNo": "12500094A",
    "model": "250ELPT ProXS DTS",
    "family": "ProXS",
    "hp": 250,
    "dealer": 36905,
    "msrp": 41115,
    "status": "In stock",
    "slug": "250elpt-pro-xs-dts"
  },
  {
    "partNo": "12500096A",
    "model": "250EXLPT ProXS DTS",
    "family": "ProXS",
    "hp": 250,
    "dealer": 37741,
    "msrp": 42045,
    "status": "Available to order",
    "slug": "250exlpt-pro-xs-dts"
  },
  {
    "partNo": "13000022A",
    "model": "300ELPT Pro XS TorqueMaster",
    "family": "ProXS",
    "hp": 300,
    "dealer": 36542,
    "msrp": 40710,
    "status": "Available to order",
    "slug": "300elpt-pro-xs-torquemaster"
  },
  {
    "partNo": "13000023A",
    "model": "300EXLPT Pro XS",
    "family": "ProXS",
    "hp": 300,
    "dealer": 37356,
    "msrp": 41615,
    "status": "Available to order",
    "slug": "300exlpt-pro-xs"
  },
  {
    "partNo": "13000177A",
    "model": "300ELPT Pro XS DTS TorqueMaster",
    "family": "ProXS",
    "hp": 300,
    "dealer": 38550,
    "msrp": 42945,
    "status": "Available to order",
    "slug": "300elpt-pro-xs-dts-torquemaster"
  },
  {
    "partNo": "13000179A",
    "model": "300EXLPT Pro XS DTS",
    "family": "ProXS",
    "hp": 300,
    "dealer": 39402,
    "msrp": 43895,
    "status": "Available to order",
    "slug": "300exlpt-pro-xs-dts"
  }
];

export const CANONICAL_RANGES: Record<string, CanonicalRange | null> = {
  "portable_2_5_to_20": {
    "count": 38,
    "dealerMin": 1298,
    "dealerMax": 5709,
    "msrpMin": 1385,
    "msrpMax": 6085
  },
  "midrange_25_to_60": {
    "count": 16,
    "dealerMin": 5093,
    "dealerMax": 13057,
    "msrpMin": 5425,
    "msrpMax": 14545
  },
  "midrange_60_to_115": {
    "count": 13,
    "dealerMin": 12040,
    "dealerMax": 17892,
    "msrpMin": 13415,
    "msrpMax": 19930
  },
  "fourstroke_75_to_115": {
    "count": 8,
    "dealerMin": 14476,
    "dealerMax": 17892,
    "msrpMin": 16125,
    "msrpMax": 19930
  },
  "proxs_115": {
    "count": 4,
    "dealerMin": 17490,
    "dealerMax": 18299,
    "msrpMin": 19485,
    "msrpMax": 20385
  },
  "hp_150_all": {
    "count": 4,
    "dealerMin": 22242,
    "dealerMax": 24475,
    "msrpMin": 24780,
    "msrpMax": 27265
  },
  "v6_175_to_250": {
    "count": 23,
    "dealerMin": 27544,
    "dealerMax": 37741,
    "msrpMin": 30685,
    "msrpMax": 42045
  },
  "hp_300": {
    "count": 8,
    "dealerMin": 36421,
    "dealerMax": 39402,
    "msrpMin": 40575,
    "msrpMax": 43895
  },
  "kicker_9_9": {
    "count": 11,
    "dealerMin": 2999,
    "dealerMax": 5198,
    "msrpMin": 3860,
    "msrpMax": 5540
  },
  "full_lineup": {
    "count": 101,
    "dealerMin": 1298,
    "dealerMax": 39402,
    "msrpMin": 1385,
    "msrpMax": 43895
  }
};
